### ISSUE TITLE
can we create tnsnames and listnername without installing oradb

### ISSUE THREAD

**Issue by supriyawishesu** [biemond/puppet#33]
Hi biemnond,

can we create only tnsnames and listerner names without installing oracle database module.

Let me know.

Appreciate your help.

**Comment by felipe1982** [comment]
Hi @biemond  - Sorry to open a dead thread, but your link is dead. I could not find anything on Augeas and TNSnames. Do have any other resource I can look at? Thanks.

**Comment by biemond** [comment]
Hi,

that works, see oradb module, not this

https://github.com/biemond/biemond-oradb/blob/master/README.md#tnsnames

only need an oracle home as requirement
