### ISSUE TITLE
datapatch command not run

### ISSUE THREAD

**Issue by winningpanthers** [biemond/puppet#56]
Oradb opatch module is great, but it is not running datapatch command after the opatch. This is causing DB not to reflect the opatch. Is this is a bug or is it something I am not doing it right?

**Comment by biemond** [comment]
Hi 

this is the wrong place for this issue see  https://github.com/biemond/biemond-oradb/issues
and is almost the same as https://github.com/biemond/biemond-oradb/issues/172

I don't have a solution how this should work on a existing DB, you cannot bring it down and patch it, on a new db this should not be a issue or necessary.

**Comment by winningpanthers** [comment]
sorry, thanks. before I close this. Is there a place where I can hardcode this datapatch command to be run right after opatch?  any advise how do I work around this issue?
